### ISSUE TITLE
Warning RARoutePickerContext

### ISSUE THREAD

**Issue by yemd** [tien/react-airplay#113]
First, excellent module!

I am experiencing a warning while using it

Module RARoutePickerContext requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.

Platform: iOS 15.2
RN Version: 0.66.1

**Comment by yemd** [comment]
Any news on the release?

**Comment by tien** [comment]
@yemd yep sorry just got my laptop back from repair, just released the version including the fix for this
