### ISSUE TITLE
iOS : 'routeChangeNotification' has been renamed to 'NSNotification.Name.AVAudioSessionRouteChange'

### ISSUE THREAD

**Issue by bhatiashantam** [tien/react-airplay#229]
Version-
 
"react-native": "0.63.4"
"react-airplay": "^1.2.0"

<img width="561" alt="issue-ss" src="https://github.com/tien/react-airplay/assets/126068389/beb0fd9a-72ea-45b5-9c52-ce78b7348c2e">

**Comment by tien** [comment]
I believe it's still under [AVAudioSession.routeChangeNotification](https://developer.apple.com/documentation/avfaudio/avaudiosession/1616493-routechangenotification).
