### ISSUE TITLE
Warning RequiresMainQueueSetup 

### ISSUE THREAD

**Issue by EduCarloto** [tien/react-airplay#40]
Hi Tien, Great work! I am testing your library with my app at the moment and I found a couple of warnings.

<img width="1301" alt="Screenshot 2021-06-30 at 10 41 56" src="https://user-images.githubusercontent.com/62381312/123948654-90f2ff80-d999-11eb-95a4-f971e411123b.png">

I have fixed just adding 

`override static func requiresMainQueueSetup() -> Bool {
      return true
    }`
    
I am happy to create a PR if you can consider it.

**Comment by tien** [comment]
Thanks for the spot. For `RAAirplayButtonViewManager` `requiresMainQueueSetup` should prob return `false` though as it doesn't export any constant nor access the `UIKit`. I'm more than happy to accept a PR of cource.
Source: https://reactnative.dev/docs/native-modules-ios#exporting-constants

**Comment by yemd** [comment]
I still get this error, has it been released?

**Comment by tien** [comment]
@yemd should be fixed already, I can't test it myself right now, unfortunately. I'm on holiday leave and don't have my laptop with me.

**Comment by yemd** [comment]
@tien It is,  mine is not exactly the same thing, after all, I will create another issue 👍
