### ISSUE TITLE
[Features request] Extend library capabilities

### ISSUE THREAD

**Issue by ericlifs** [tien/react-airplay#61]
Hey @tien, how are you?

I see your library as the ultimate and most up-to-date Airplay library for react-native and I'm really willing to use it in my apps. I have a list of features I think will add a lot of value to this already awesome package. I'm not sure if they are possible to implement, maybe you can confirm that:

- Add a connect method that you can call whenever you want. This will allow the devs to use any custom component (or user interaction) to show up the list of devices you can connect to (and not just the AirplayButton that comes with the library). I have a custom icon component on my app that I want to use to connect to Airplay (and not rely on the AirplayButton) because it has some custom size and styles that I want to apply.

- Add a disconnect method that you can call whenever you want. I'm facing a really big issue on my app where I'm having some videos that should be "Airplayeable" and other videos that I don't want them to be "AirPlayeable". The thing is that even though I'm setting the videos to don't allow the external playback, they are still airplayed to the tvOS no matter what because the connection is already stablished. The best way of fixing this (I think) is to disconnect that connection when the video ends (you can read more about this issue on https://github.com/react-native-video/react-native-video/issues/2464)

Let me know if I can help you somehow please!

**Comment by tien** [comment]
I've added a new method `showRoutePicker` to programmatically show the airplay menu. As for programmatically disconnecting air. For disconnecting a current airplay session that's not possible, unfortunately.
