### ISSUE TITLE
Airplay stops when device screen turns off

### ISSUE THREAD

**Issue by redefinered** [tien/react-airplay#97]
Thanks for a great lib!

I'm using this for an application I am building. Works great all around except that airplay stops when phone sleeps, or when I lock the device.

Background modes is already activated in Xcode capabilities section and "_Audio, Airplay, and Picture in Picture_" options is already enabled.

![Screen Shot 2021-11-25 at 6 24 56 PM](https://user-images.githubusercontent.com/5173630/143424565-dd81ec55-2c59-454c-90bf-206f1fb7d33e.png)

**Comment by tien** [comment]
This library only uses the native iOS Airplay button. So it doesn't really control playback behaviour. Hope you can find the following links helpful:

https://stackoverflow.com/questions/13206952/is-there-a-way-to-keep-airplay-running-if-the-device-auto-sleeps-auto-locks/14823268#14823268
https://stackoverflow.com/questions/12814574/how-to-support-airplay-in-the-background-in-ios6
https://github.com/react-native-video/react-native-video/issues/41

**Comment by yemd** [comment]
> 

What player are you using it with? I am using react-native-video, if you do too, there is an background playback prop to set on top of the Xcode setup

**Comment by redefinered** [comment]
@yemd yes, I actually managed to fix my issue with that prop. But thanks anyway. Closing this issue now!
