### ISSUE TITLE
Not working on Android

### ISSUE THREAD

**Issue by stijnvanderlaan** [tien/react-airplay#99]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

We implemented it and it works great on iOS, but on Android we got the next error:

```
TypeError: null is not an object (evaluating 'RARoutePickerContext.showRoutePicker')
```

We got it to work by removing all code related to showRoutePicker.

**Comment by tien** [comment]
Thanks for the report, I'll have this fixed sometime over this weekend.
